### ISSUE TITLE
Infografia_Hilos_Pedro

### ISSUE THREAD

**Issue by PedroGarcia15** [SistemasTecTlaxiaco/infografia-de-hilos-PedroGarcia15#2]
[Infografia hilos (3).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-PedroGarcia15/files/15135366/Infografia.hilos.3.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, has obtenido un 20% de 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
